server:
  port: 8080

github:
  api:
    token: ${GITHUB_API_TOKEN:}
    base-url: https://api.github.com
    timeout: 30000

scoring:
  strategy:
    version: v1
  stars:
    cap: 10000
    weight: 0.45
  forks:
    cap: 10000
    weight: 0.2
  freshness:
    half-life-days: 90
    weight: 0.35

logging:
  level:
    com.gerard.githubreposcorer.scoring: DEBUG
